// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pngypsvzfgbrlcsgslnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZ3lwc3Z6Zmdicmxjc2dzbG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDkyODgsImV4cCI6MjA3MzQ4NTI4OH0.LuNmn0DDaBwMUtTfZuuyZIinN5F4sxOqx9FbHrHBUMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});